export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER';
export const RESET_COUNTER = 'RESET_COUNTER';
export const INCREMENT_COUNTER_ASYNC = 'INCREMENT_COUNTER_ASYNC';
export const LOAD_API_RESULTS = 'LOAD_API_RESULTS';
export const API_SUCCESS = 'API_SUCCESS';
export const API_FAILURE = 'API_FAILURE';
