export const LOAD_ARTIST_LIST = 'LOAD_ARTIST_LIST';
export const LOADED_ARTIST_LIST = 'LOADED_ARTIST_LIST';
export const FAILED_LOADING_ARTIST_LIST = 'FAILED_LOADING_ARTIST_LIST';

export const LOAD_ARTIST_DETAIL = 'LOAD_ARTIST_DETAIL';
export const LOADED_ARTIST_DETAIL = 'LOADED_ARTIST_DETAIL';
export const FAILED_LOADING_ARTIST_DETAIL = 'FAILED_LOADING_ARTIST_DETAIL';

export const EDIT_ARTIST_DETAIL = 'EDIT_ARTIST_DETAIL';
export const EDITED_ARTIST_DETAIL = 'EDITED_ARTIST_DETAIL';
export const FAILED_EDITING_ARTIST_DETAIL = 'FAILED_EDITING_ARTIST_DETAIL';

export const SET_ID = 'SET_ID';

export const SET_INPUT_TEXT = 'SET_INPUT_TEXT';
export const CLEAR_INPUT_TEXT = 'CLEAR_INPUT_TEXT';

export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
